"""empty message

Revision ID: 64d80d8ac661
Revises: 
Create Date: 2023-09-22 12:32:34.636932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d80d8ac661'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户编号'),
    sa.Column('username', sa.String(), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(), nullable=False, comment='二进制哈希密码'),
    sa.Column('display_name', sa.String(), nullable=False, comment='显示名'),
    sa.Column('mail', sa.String(), nullable=True, comment='邮箱'),
    sa.Column('account_type', sa.Enum('local', 'xysso', name='accounttype'), nullable=False, comment='账户类型'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
