"""apps 表结构大调整

Revision ID: 2602ce4fdd1b
Revises: 3c1ba38bc114
Create Date: 2023-10-12 10:45:37.163786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2602ce4fdd1b"
down_revision: Union[str, None] = "3c1ba38bc114"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.Column(
            "order", sa.Integer(), autoincrement=True, nullable=False, comment="排序值"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="角色名"),
        sa.Column("admin", sa.Boolean(), nullable=False, comment="是否为管理员"),
        sa.Column("data_scope", sa.Integer(), nullable=False, comment="数据权限范围"),
        sa.Column("comment", sa.String(), nullable=True, comment="备注"),
        sa.Column("create_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.Column("key", sa.String(), nullable=True, comment="索引key"),
        sa.Column(
            "order", sa.Integer(), autoincrement=True, nullable=False, comment="排序值"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_key"), "role", ["key"], unique=True)
    op.create_table(
        "userroleassociation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "action",
        sa.Column("name", sa.String(), nullable=False, comment="名称"),
        sa.Column("value", sa.String(), nullable=False, comment="权限值"),
        sa.Column("api", sa.String(), nullable=True, comment="接口地址"),
        sa.Column("method", sa.String(), nullable=True, comment="请求方式"),
        sa.Column("permission_id", sa.String(), nullable=False, comment="属于哪个权限集"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "department",
        sa.Column("actived", sa.Boolean(), nullable=False, comment="是否激活状态"),
        sa.Column("owner_id", sa.Integer(), nullable=False, comment="负责人"),
        sa.Column("parent_id", sa.Integer(), nullable=True, comment="父部门"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.Column(
            "order", sa.Integer(), autoincrement=True, nullable=False, comment="排序值"
        ),
        sa.Column("key", sa.String(), nullable=True, comment="索引key"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["department.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_department_key"), "department", ["key"], unique=True)
    op.create_table(
        "menu",
        sa.Column("icon", sa.String(), nullable=True, comment="菜单图标"),
        sa.Column("name", sa.String(), nullable=False, comment="菜单名称"),
        sa.Column("is_link", sa.Boolean(), nullable=False, comment="是否是外链"),
        sa.Column("route_path", sa.String(), nullable=True, comment="路由地址"),
        sa.Column("component", sa.String(), nullable=True, comment="组件地址"),
        sa.Column("component_name", sa.String(), nullable=True, comment="组件名"),
        sa.Column("enabled", sa.Boolean(), nullable=False, comment="开关状态"),
        sa.Column("hidden", sa.Boolean(), nullable=False, comment="是否隐藏"),
        sa.Column("permission_id", sa.String(), nullable=True, comment="绑定的权限id"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.Column(
            "order", sa.Integer(), autoincrement=True, nullable=False, comment="排序值"
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "userdepartmentassociation",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("create_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.key"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "dictionary",
        sa.Column(
            "order", sa.Integer(), autoincrement=True, nullable=False, comment="排序值"
        ),
    )
    op.alter_column(
        "dictionary",
        "id",
        existing_type=sa.INTEGER(),
        comment="主键",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('dictionary_id_seq'::regclass)"),
    )
    op.alter_column(
        "dictionary",
        "key",
        existing_type=sa.VARCHAR(),
        nullable=True,
        comment="索引key",
        existing_comment="字典编号",
    )
    op.drop_column("dictionary", "sort")
    op.add_column(
        "dictionarykeyvalue",
        sa.Column(
            "order", sa.Integer(), autoincrement=True, nullable=False, comment="排序值"
        ),
    )
    op.alter_column(
        "dictionarykeyvalue",
        "id",
        existing_type=sa.INTEGER(),
        comment="主键",
        existing_comment="键值编号",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("dictionarykeyvalue", "sort")
    op.alter_column(
        "user",
        "id",
        existing_type=sa.INTEGER(),
        comment="主键",
        existing_comment="用户编号",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "id",
        existing_type=sa.INTEGER(),
        comment="用户编号",
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.add_column(
        "dictionarykeyvalue",
        sa.Column(
            "sort", sa.INTEGER(), autoincrement=False, nullable=False, comment="排序编号"
        ),
    )
    op.alter_column(
        "dictionarykeyvalue",
        "id",
        existing_type=sa.INTEGER(),
        comment="键值编号",
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("dictionarykeyvalue", "order")
    op.add_column(
        "dictionary",
        sa.Column(
            "sort", sa.INTEGER(), autoincrement=False, nullable=False, comment="排序编号"
        ),
    )
    op.alter_column(
        "dictionary",
        "key",
        existing_type=sa.VARCHAR(),
        nullable=False,
        comment="字典编号",
        existing_comment="索引key",
    )
    op.alter_column(
        "dictionary",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="主键",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('dictionary_id_seq'::regclass)"),
    )
    op.drop_column("dictionary", "order")
    op.drop_table("userdepartmentassociation")
    op.drop_table("menu")
    op.drop_index(op.f("ix_department_key"), table_name="department")
    op.drop_table("department")
    op.drop_table("action")
    op.drop_table("userroleassociation")
    op.drop_index(op.f("ix_role_key"), table_name="role")
    op.drop_table("role")
    op.drop_table("permission")
    # ### end Alembic commands ###
