"""app dictionary 建表

Revision ID: 3c1ba38bc114
Revises: b96a5b921877
Create Date: 2023-10-11 08:52:33.123897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1ba38bc114'
down_revision: Union[str, None] = 'b96a5b921877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False, comment='字典编号'),
    sa.Column('name', sa.String(), nullable=False, comment='字典名'),
    sa.Column('type', sa.Integer(), nullable=False, comment='值类型'),
    sa.Column('enable', sa.Boolean(), nullable=False, comment='启用/禁用'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序编号'),
    sa.Column('comment', sa.String(), nullable=False, comment='备注'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dictionary_key'), 'dictionary', ['key'], unique=True)
    op.create_table('dictionarykeyvalue',
    sa.Column('id', sa.Integer(), nullable=False, comment='键值编号'),
    sa.Column('name', sa.String(), nullable=False, comment='键名'),
    sa.Column('value', sa.String(), nullable=False, comment='值'),
    sa.Column('type', sa.Integer(), nullable=False, comment='值类型'),
    sa.Column('enable', sa.Boolean(), nullable=False, comment='启用/禁用'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序编号'),
    sa.Column('color', sa.String(), nullable=True, comment='颜色'),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['dictionary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dictionarykeyvalue')
    op.drop_index(op.f('ix_dictionary_key'), table_name='dictionary')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
