"""apps 表结构大调整

Revision ID: b2f89a49027b
Revises: 2602ce4fdd1b
Create Date: 2023-10-12 10:56:18.012579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2f89a49027b"
down_revision: Union[str, None] = "2602ce4fdd1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userroleassociation",
        sa.Column("user_id", sa.Integer(), nullable=False, comment="用户id"),
    )
    op.add_column(
        "userroleassociation",
        sa.Column("role_id", sa.String(), nullable=False, comment="角色id"),
    )
    op.create_foreign_key(None, "userroleassociation", "user", ["user_id"], ["id"])
    op.create_foreign_key(None, "userroleassociation", "role", ["role_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userroleassociation", type_="foreignkey")
    op.drop_constraint(None, "userroleassociation", type_="foreignkey")
    op.drop_column("userroleassociation", "role_id")
    op.drop_column("userroleassociation", "user_id")
    # ### end Alembic commands ###
