"""app user mail默认值删除

Revision ID: b96a5b921877
Revises: a9d4b7dc2217
Create Date: 2023-10-11 03:58:09.705051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96a5b921877'
down_revision: Union[str, None] = 'a9d4b7dc2217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='显示名')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='显示名')
    # ### end Alembic commands ###
